### PR TITLE
close-menu optimization

### PR DESCRIPTION
**Pull request by SYwaves**
Reorganize .close-menu properties to minimize specificity spillover.

Remove useless(?) ::after element on side-bar.

Possibly breaking changes. Don't merge yet until verified.

### CODE REVIEW

**Review by emmiegit — APPROVED** [review]

**Review by 6309304695 — APPROVED** [review]
Color #000006

**Comment by emmiegit** [comment]
@SYwaves has this been verified?

**Comment by SYwaves** [comment]
As far as I've been able to test, it seems fine.

**Comment by emmiegit** [comment]
Cool, merge and deploy at will then.

**Pull request merged**
