### PR TITLE
Add redaction character font

### PR DESCRIPTION
**Pull request by rossjrw**
None of the fonts in sigma.css provide a FULL BLOCK character, causing it to fall back to browser default. On some systems (Fedora and Android at least), this default character is square, which breaks immersion by making redacted text look like it's about twice as long as it actually is:

4-digit SCP number:
image

This PR addresses this by adding a from-scratch font that provides a FULL BLOCK character with roughly the same dimensions as `0` from Inter. Font is licensed SIL OFL and the copyright is attributed to The SCP Wiki.

I have tweaked the top/bottom borders of the character to better align aesthetically with surrounding text, and the left/right borders extend slightly beyond the character's width to cover subpixel lines that are sometimes visible between adjacent characters.

It's not a variable font, I don't know how to do that. A future improvement could make it act similarly to Inter's variables.

image

Demo on https://scp-sandbox-3.wikidot.com/croquemtest revision 1501

### CODE REVIEW

**Comment by leo60228** [comment]
Since the font contains only a single codepoint, it'd probably make sense to set `unicode-range` for efficiency reasons?

**Comment by rossjrw** [comment]
@leo60228 TIL, 10/10 suggestion

**Comment by Kufat** [comment]
LGTM but I'm hesitant to officially approve because of my limited CSS experience

**Review by emmiegit — APPROVED** [review]
Good change. We should also announce this to INT.

**Pull request merged**
